openshift/image-based-install-operator

- controllers/clusterconfig_controller.go
- controllers/clusterconfig_controller_test.go
This prevents the BMH from accidentally being used later and rebooting the host and from the host rebooting when the clusterconfig is removed.
Resolves https://issues.redhat.com/browse/MGMT-15247
> Detach BMH after it is provisioned

- api/v1alpha1/clusterconfig_types.go
- config/crd/bases/relocation.openshift.io_clusterconfigs.yaml
- controllers/clusterconfig_controller.go
- controllers/clusterconfig_controller_test.go
Resolves https://issues.redhat.com/browse/MGMT-15245
cc @eranco74
> Add nmconnection files from the referenced configmap

- Makefile
- README.md
This option can be confusing next to the option to remove the controller and clean the CRDs altogether.
> Removing the option to only remove the CRD

- controllers/clusterconfig_controller.go
- controllers/clusterconfig_controller_test.go
- go.mod
Ensure the extra manifest data can be yaml.Unmarshal'd
Resolves https://issues.redhat.com/browse/MGMT-15602
> Validate extra manifest yaml

- controllers/clusterconfig_controller.go
- controllers/clusterconfig_controller_test.go
Resolves https://issues.redhat.com/browse/MGMT-15697
cc @achuzhoy
> Correctly set TypeMeta on namespaces

- bundle.Dockerfile
- bundle/manifests/extensions.hive.openshift.io_imageclusterinstalls.yaml
- bundle/manifests/image-based-install-config_v1_service.yaml
- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
- bundle/manifests/webhook-service_v1_service.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/manifests/bases/image-based-install-operator.clusterserviceversion.yaml
- config/samples/extensions_v1alpha1_imageclusterinstall.yaml
This is required for MCE to deploy the operator.
Resolves https://issues.redhat.com/browse/MGMT-16513
After this `make bundle` must be run when changing deploy files or APIs
> MGMT-16513: Add bundle files

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
Validate pull secret
Pass the pullSecret as part of the cluster config instead of writing the secret to manifest dir
> MGMT-16667: Validate pull secret

- cmd/manager/main.go
- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
- go.mod
- internal/certs/certs.go
- internal/certs/certs_test.go
- internal/credentials/credentials.go
- internal/credentials/credentials_test.go
- vendor/golang.org/x/crypto/bcrypt/base64.go
- vendor/golang.org/x/crypto/bcrypt/bcrypt.go
- vendor/modules.txt
Create a password for the kubeadmin user and store it in a secret
Set  the ClusterDeployment in the secret owner ref
Add the password hash to the SeedReconfiguration
> MGMT-16714 Create kubeadmin password

- Makefile
- hack/crds/baremetalhosts.yaml
- hack/crds/clusterdeployments.yaml
- hack/crds/clusterimagesets.yaml
- hack/integration-test/clusterdeployment.yaml
- hack/integration-test/clusterimageset.yaml
- hack/integration-test/imageclusterinstall.yaml
- hack/integration-test/namespace.yaml
- hack/integration-test/pull-secret.json
- hack/integration-test/validate.sh
- hack/integration-test/wait-for-ready.sh
Running `make run-integration-test` will now deploy the operator, create the required CRDs, create the CRs needed for a simple test of the operator, and ensure the ISO can be downloaded.
https://issues.redhat.com/browse/MGMT-16931
> MGMT-16931: Add an integration test

- api/v1alpha1/imageclusterinstall_types.go
- bundle/manifests/extensions.hive.openshift.io_imageclusterinstalls.yaml
- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
- config/crd/bases/extensions.hive.openshift.io_imageclusterinstalls.yaml
- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
- internal/utils/utils.go
[MGMT-17087](https://issues.redhat.com//browse/MGMT-17087): validate that bmh has at least one ip in provided machine network
Changing machine_network to machineNetwork according to install-config
> MGMT-17087: validate that bmh has at least one ip in provided machine network

- bundle/manifests/extensions.hive.openshift.io_imageclusterinstalls.yaml
- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
This was missed in #61 and #62 
cc @eranco74
> Update bundle with print fields for image cluster install

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
In order for the ACM hub DR solution to include our required ConfigMaps and Secrets, they must be labeled with
`cluster.open-cluster-management.io/backup=true`.
Ensure the label is present on each reconcile.
The ImageClusterInstall is already covered because all resources in the `hive.openshift.io` group are automatically backed up.
Resolves https://issues.redhat.com/browse/ACM-13449
> ACM-13449: Label ConfigMaps and Secrets for backup

- bundle/manifests/extensions.hive.openshift.io_imageclusterinstalls.yaml
- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
Missed this in https://github.com/openshift/image-based-install-operator/pull/78
> Update bundle after removing version

- OWNERS
> NO-ISSUE: Add eliorerz to OWNERS file

- controllers/conditions.go
- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
[MGMT-18834](https://issues.redhat.com//browse/MGMT-18834): validate before each patch if something changed before running patch itself.
Add logging for each patch operation
> MGMT-18834: validate before each patch if something changed before running patch itself.

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
Use the ICI.UID instead of the ICI.name
> MGMT-18619: Obfuscate config ISO url

- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
> MGMT-18219: Use DataImage instead of BMH spec.image.URL

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
> MGMT-18906: Fix reboot annotation to do a soft reboot

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
Set the ici.Status.BareMetalHostRef only after the BMH provisioning is set by IBIO
> MGMT-18899: Reboot externally provisioned node if it was already powered on

- api/v1alpha1/imageclusterinstall_webhook.go
- api/v1alpha1/imageclusterinstall_webhook_test.go
- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
This change also removes the handleing for BMH update post install since the effect of such update is unknown
Note that the webhook doesn't handle changes to resources referenced by the ICI
> MGMT-18876: Update admission controller to block changes to ICI once the installation started

- controllers/conditions.go
- controllers/imageclusterinstall_controller.go
- internal/credentials/credentials.go
Currently this log line show up 52 times per cluster we install
> Reduce log spam

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
- hack/integration-test/validate.sh
> MGMT-18909: Delete DataImage on ICI deletion

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
The finalizer will be removed by the controller if the referenced BareMetalHost or the DataImage no longer exists.
> MGMT-19012: The controller shouldn't remove the finalizer as long the dataImage exists

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
There's a race between the DataImage creation and the reboot annotation added in updateBMHProvisioningState
This PR adds a check that the DataImage creationTimestamp is more than the `DataImageCoolDownPeriod` ago (set to 1 second by default).
In case the the dataImage was created withing the `DataImageCoolDownPeriod` the controller will
return early and requeue the ICI CR after the `DataImageCoolDownPeriod`.
This should prevent IBIO from adding the reboot annotation before BMO cached client notice that a DataImage exists.
> MGMT-19154: BMO never mounted dataimage into IBI provisioned SNO

- controllers/imageclusterinstall_controller.go
Make sure the clusterInfo file exists in case the bootTime is set, 
this would ensure the clusterInfo is regenerated in case the IBIO pod was restarted
> MGMT-19341: IBIO isn't creating the config after restart for ICI with bootTime set

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
Sometimes if bmh has externally-provisioned and only true there is a chance that we will create data image before bmh was started so after creating it it will be mounted without a need to reboot the node. Though we will still set reboot node flag and in case machine boots quickly we can get reboot in the middle of the installation.
We should verify that data image was not mounted before setting reboot flag
> MGMT-19375: don't reboot the node if data image was mounted already

- doc/reinstall.md
Document how to reinstall a cluster using the resources from an existing install.
> MGMT-19487: Add documentation for cluster reinstall

- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Resolves https://issues.redhat.com/browse/ACM-16354
> ACM-16354: Remove resource limits from IBIO deployment

- internal/installer/reinstall.go
- internal/installer/reinstall_test.go
Allow most of the reconfig manifest to change based on the current data in the ClusterDeployment and ImageClusterInstall, but some fields must not change between install and reinstall.
This commit validates these fields match between the manifest generated based on the new config and the manifest in the secret from the original install.
Resolves https://issues.redhat.com/browse/MGMT-19209
> MGMT-19209: Validate important fields have not changed on reinstall

- Makefile
- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/MGMT-19745
> MGMT-19745: Regenerate bundle for tmp dir change

- bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
- bundle/manifests/image-based-install-webhook_v1_service.yaml
- vendor/modules.txt
https://issues.redhat.com/browse/MGMT-19972
> MGMT-19972: Regenerate bundle after webhook rename

- renovate.json
Resolves https://issues.redhat.com/browse/MGMT-20091
cc @giladravid16 @eranco74
> MGMT-20091: Add renovate.json to disable module updates

- controllers/imageclusterinstall_controller.go
- controllers/imageclusterinstall_controller_test.go
Updates error handling to manage DataImage in deletion process better.
When the deletion timestamp is non-zero, a warning is logged, the status is updated, and a requeueAfter result with a one-minute delay is returned. 
This check was moved out of `ensureBMHDataImage` method, to allow early and specific handling for such case since it may conflict with the  requirementsMet status condition set by validateBMH method.
Additionally, the return type of the validateBMH method is simplified to streamline error handling.
> MGMT-20024: fix the hot-loop in case dataImage hang while deleting

- .tekton/image-based-install-operator-mce-29-push.yaml
Resolves https://issues.redhat.com/browse/ACM-20987
> ACM-20987: Enable multi-arch konflux builds
