openshift/image-based-install-operator

README.md

The existing steps would fail to deploy the cluster config CR because the CRDs wouldn't have been created yet.

Clarify deployment steps in readme

---

config/rbac/role.yaml
controllers/clusterconfig_controller.go

This is required to read the secrets referrenced in the clusterconfig spec. Without this referencing a secret in the clusterconfig would fail the reconcile with an rbac error.
cc @achuzhoy

Add secrets reader permissions

---

config/manager/manager.yaml

This is required for `make deploy` to properly substitute the image using the `IMG` env var.
Without this `quay.io/carbonin/cluster-relocation-service:latest` is used unconditionally.
cc @achuzhoy

Make kustomize image substitution work properly

---

config/manager/manager.yaml

Configure service serving certs via annotation and mount the resulting secret into the service container
Resolves https://issues.redhat.com/browse/MGMT-15257

Serve images over https

---

controllers/clusterconfig_controller.go
controllers/clusterconfig_controller_test.go

The cluster relocation operator requires the cluster relocation CR to be named "cluster"
ref: https://github.com/RHsyseng/cluster-relocation-operator/blob/3fa806e8136f8fe02e8aab3abec6878a28efedbc/controllers/clusterrelocation_controller.go#L280
Resolves https://issues.redhat.com/browse/MGMT-15523
cc @achuzhoy

Use correct cluster relocation CR name

---

controllers/clusterconfig_controller.go
controllers/clusterconfig_controller_test.go

Before this change this service was not providing a manifest for the target namespace of any of the resources. Additionally the referenced secret could be in namespaces separate from the CluterConfig.
This commit creates a single namespace manifest and uses that namespace for all of the created resources (clusterrelocation and secrets).
This will make the resulting resources on the relocated cluster easier to find and understand when multiple clusters are being relocated using the same hub.
Resolves https://issues.redhat.com/browse/MGMT-15488

Add namespace and use it for all resources

---

controllers/clusterconfig_controller.go
controllers/clusterconfig_controller_test.go

Split the cluster config files (Namespace, ClusterRelocation, Secrets), extra manifests, and nmconnection files in to separate directories.
Resolves https://issues.redhat.com/browse/MGMT-15603

Use directories for different file types

---

api/v1alpha1/groupversion_info.go
controllers/clusterconfig_controller.go
controllers/clusterconfig_controller_test.go
internal/filelock/filelock.go
internal/filelock/filelock_test.go
internal/imageserver/imageserver.go

Adds a finalizer to clusterconfig resources that allows the controller
to clean up the local files for that config and remove the image
reference from a linked BMH.
Resolves https://issues.redhat.com/browse/MGMT-15282

MGMT-15282: Remove files and deprovision BMH when clusterconfig is removed

---

PROJECT
api/v1alpha1/groupversion_info.go
cmd/manager/main.go
config/crd/bases/extensions.hive.openshift.io_imageclusterinstalls.yaml
config/crd/kustomization.yaml
config/crd/patches/hive_contract_label.yaml
config/rbac/imageclusterinstall_editor_role.yaml
config/rbac/imageclusterinstall_viewer_role.yaml
config/rbac/role.yaml
config/samples/extensions_v1alpha1_imageclusterinstall.yaml
config/samples/kustomization.yaml
config/webhook/manifests.yaml
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go
controllers/suite_test.go

This PR makes a few changes to ensure the new hive APIs are usable.
It adds the hive contract label to the CRD which is required for hive to recognize this type as a valid
ClusterInstall sub-type. Without this the hive admission webhook returns
an error like:
```
Error from server (Invalid): error when creating "cluster.yaml": admission webhook "clusterdeploymentvalidators.admission.hive.openshift.io" denied the request: ClusterDeployment.hive.openshift.io "test-sno" is invalid: spec.clusterInstallRef.kind: Unsupported value: "ImageClusterInstall": supported values: "extensions.hive.openshift.io/v1beta1, Kind=AgentClusterInstall", "hiveinternal.openshift.io/v1alpha1, Kind=FakeClusterInstall"
```
It also changes the API group to extensions.hive.openshift.io. This is required so that hive …

MGMT-16618: Make hive APIs work

---

api/v1alpha1/imageclusterinstall_webhook.go
api/v1alpha1/imageclusterinstall_webhook_test.go

Previously this was failing for status, and is now failing for metadata (specifically when removing the finalizer).
Resolves https://issues.redhat.com/browse/MGMT-16554

MGMT-16554: Only fail the admission webhook if the spec was changed

---

Makefile
PROJECT
README.md
cmd/manager/main.go
cmd/server/main.go
config/default/kustomization.yaml
config/manager/manager.yaml
config/manifests/kustomization.yaml
config/prometheus/monitor.yaml
config/rbac/leader_election_role.yaml
config/rbac/leader_election_role_binding.yaml
config/rbac/role_binding.yaml
config/rbac/service_account.yaml
config/webhook/service.yaml
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go
controllers/suite_test.go
go.mod
internal/imageserver/imageserver.go
internal/imageserver/imageserver_test.go

This commit changes any names referencing relocation to something that agrees with the new repo name. This includes the module/import path as well as the operator namespace and all the object names in the operator deploy manifests.
This doesn't handle the group name as that is involved with the hive API work and is solved in https://github.com/openshift/image-based-install-operator/pull/27
Resolves https://issues.redhat.com/browse/MGMT-16614

MGMT-16614: Update names referencing relocation

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

Before this attempting to apply this secret directly to the spoke cluster was failing because of this additional metadata.
Resolves https://issues.redhat.com/browse/MGMT-16646

MGMT-16646: Clear the pull secret metadata

---

controllers/imageclusterinstall_controller.go

When using the cluster name from the spec we might override kubeconfig that belong to another cluster that happens to share the same cluster name

Use the cluster deployment name for the kubeconfig secret name

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go
internal/certs/certs.go

Prior to this change, IBIO renders the cluster crypto 4 times in case of happy flow. It's useless time consuming and error prone (we might accidintly override the cluster kubeconfig) This change will generate new crypto in case the current cluster crypto doesn't match the current cluster name and basedomain.

MGMT-16650 Regenerate cluster crypto only when needed

---

bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

Previously the ConfigMap referenced by NetworkConfigRef was expected to
contain nmconnection files, but this was s workaround until nmstate
could be run during the reconfiguration process.
This commit sets the contents of the "network-config" configmap key to
the `RawNMStateConfig` field in the SeedReconfiguration struct.
Resolves https://issues.redhat.com/browse/MGMT-16668

MGMT-16668: Use nmstate for network configuration

---

bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/imageclusterinstall_controller.go
internal/credentials/credentials.go

This is required to set the owner reference for the credential secrets to the cluster deployment.
Without this reconcile errors with:
```
2024-02-15T13:27:42Z	ERROR	Reconciler error	{"controller": "imageclusterinstall", "controllerGroup": "extensions.hive.openshift.io", "controllerKind": "ImageClusterInstall", "ImageClusterInstall": {"name":"ibi-test","namespace":"ibi-test"}, "namespace": "ibi-test", "name": "ibi-test", "reconcileID": "4130c019-a6b0-4131-9d6e-e51fff203cfc", "error": "failed to write input data: failed to ensure admin password secret: failed to create kubeadmin password secret: failed to create secret: secrets \"ibi-test-admin-password\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```
Resolves …

MGMT-16930: Fix credentials secret owner RBAC

---

bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/manager/manager.yaml

In scale test environments (~3600 BMHs and cluster deployments) the memory usage quickly grows to around 500Mi.
Resolves https://issues.redhat.com/browse/ACM-9925

ACM-9925: Increase resource requests and limits

---

Makefile

This seems to be needed for the integration CI tests. kubectl isn't present on the image built for CI tests

NO-ISSUE: Use oc over kubectl in Makefile deploy targets

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

Previously this was incorrectly set to the kubeconfig secret name. This was causing constant reconciles as the values seem to be copied from the cluster install to the cluster deployment which we then reset (as we are setting both).

Set kubeadminPasswordSecret name correctly

---

api/v1alpha1/imageclusterinstall_types.go
controllers/conditions.go
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

~~Built on https://github.com/openshift/image-based-install-operator/pull/52~~ Merged
~~Requires https://github.com/openshift/hive/pull/2267~~ Merged
Hive will copy the cluster metadata, set the installed field, and will also only set conditions if the message or reason was updated.
Resolves https://issues.redhat.com/browse/MGMT-17619

MGMT-17619: Align cluster install usage with hive expectations

---

controllers/imageclusterinstall_controller.go
internal/credentials/credentials.go
internal/credentials/credentials_test.go

[MGMT-17597](https://issues.redhat.com//browse/MGMT-17597): Rescheduling IBIO after install begins invalidates kubeconfig and certs
Saving crypto keys in secret and reading them from it in case kubeconfig url is valid

MGMT-17597: Rescheduling IBIO after install begins invalidates kubeconfig and certs

---

Dockerfile
bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/manager/manager.yaml

This also involved changing some of where the resulting executables were placed which then required a bundle update.
WIP until https://github.com/openshift/image-based-install-operator/pull/69 is merged.

ACM-13444: Update images to use registry.access.redhat.com bases

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

[MGMT-18553](https://issues.redhat.com//browse/MGMT-18553): In order to use same nmstate configuration logic as bmh we will use secret provided as reference in
PreprovisioningNetworkDataName in bmh spec, in case there is no bmh we will still use same configmap as before

MGMT-18553: use same nmstate configuration logic as bmh

---

api/v1alpha1/imageclusterinstall_types.go
config/crd/bases/extensions.hive.openshift.io_imageclusterinstalls.yaml

The only use of this field was removed in
b44908563ec35f5cc02647181e1f382cce107c6c and if we need something from the version in the future we should be getting it from the ClusterImageSet

NO-ISSUE: Remove ICI version field

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

[MGMT-18704](https://issues.redhat.com//browse/MGMT-18704): Slow performance while attempting to Install many SNOs via Image Cluster Installs with IBI Operator
We should not try to connect to CVO if bmh is not provisioned, this causes us to stuck in spoke client for timeout as cluster can't be started yet

MGMT-18704: Slow performance while attempting to Install many SNOs via Image Cluster Installs with IBI Operator

---

controllers/imageclusterinstall_controller.go
internal/monitor/monitor.go
internal/monitor/monitor_test.go

MGMT-18860: IBIO report installtion complete although the cluster is still reconfiguring
Create new cm in order to get creation timestamp that will point us to
the time when cluster started to run
Check conditions in CVO and verify that at least one was changed after
cm creation timestamp

MGMT-18860: create ibio start cm

---

controllers/imageclusterinstall_controller.go
internal/credentials/credentials.go
internal/credentials/credentials_test.go

[MGMT-18865](https://issues.redhat.com//browse/MGMT-18865): always read crypto values from secret and not from seedreconfiguration object

MGMT-18865: always read crypto values from secret and not from seedreconfiguration object

---

api/v1alpha1/imageclusterinstall_types.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/extensions.hive.openshift.io_imageclusterinstalls.yaml
bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/crd/bases/extensions.hive.openshift.io_imageclusterinstalls.yaml
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

Following this change static network config is supported only via PreprovisioningNetworkDataName on the BMH spec
This should reduce the code complexity and confusion e.g. https://issues.redhat.com/browse/CNF-14123

MGMT-18662 Remove static netowrk ref from the ICI

---

controllers/conditions.go
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

[MGMT-18898](https://issues.redhat.com//browse/MGMT-18898): Allow transition from ClusterInstallationTimedOut to installComplete
In case installation timed out but reconcilation ran we still want to validate if cluster managed to be installed or not, in case it finished successfully after timeout we will set installed

MGMT-18898: Allow transition from ClusterInstallationTimedOut to installComplete

---

controllers/imageclusterinstall_controller.go

Any time r.Log is used the ImageClusterInstall name and namespace are not being logged with the message which makes them much less useful.

NO-ISSUE: Use logger with fields everywhere

---

api/v1alpha1/imageclusterinstall_types.go
controllers/conditions.go
controllers/imageclusterinstall_controller_test.go

[MGMT-18950](https://issues.redhat.com//browse/MGMT-18950): Set condition stopped to false in case of timeout
As we allow to update status from timeout to installed we should not set stopped installation flag to false on timeout

MGMT-18950: Set condition stopped to false in case of timeout

---

api/v1alpha1/imageclusterinstall_types.go
bundle/manifests/extensions.hive.openshift.io_imageclusterinstalls.yaml
bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/crd/bases/extensions.hive.openshift.io_imageclusterinstalls.yaml
controllers/conditions.go
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

* Since we no longer set the image URL remove ConfigurationImageURL from ICI status
* Disable AutomatedCleaningMode earlier
* Add const for a soft reboot annotation value
* Set RequirementsMet condition in case of missing clusterDeploymentRef
* Initialize conditions prior to other logic

Cleanup & minor refactor

---

controllers/conditions.go
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

* Reconcile will be triggered once the BMH get updated
* Fixed logging format
* Improve mapBMHToICI using list options to filter the relevant ICI
* Remove useless warning logging saying "Can't find DataImage"
* Delete test that validate the behavior in case of spec changes after the installation started
Spec update during installation isn't supported and bllocked by an addmission webhook hence no need to cover this in a test

MGMT-19034 IBIO shouldn't requeue in case BMH hasn't started yet

---

api/v1alpha1/imageclusterinstall_types.go
bundle/manifests/extensions.hive.openshift.io_imageclusterinstalls.yaml
bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/crd/bases/extensions.hive.openshift.io_imageclusterinstalls.yaml

Previously this was "extraManifestsRef" which was a mistake
Resolves https://issues.redhat.com/browse/ACM-14649

ACM-14649: Correct the json field name for extraManifestsRefs

---

Dockerfile
bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/manager/manager.yaml

1. Updating memory limit to 1500miB
2. Adding flag for golang garbage collection in order to free memory faster

MGMT-19033: IBIO OOM while provisioning many clusters

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

There's a race between the DataImage creation and the reboot annotation added in updateBMHProvisioningState This PR adds a check that the DataImage creationTimestamp is more than the DataImageCoolDownPeriod ago (set to 1 second by default). In case the the dataImage was created withing the DataImageCoolDownPeriod the controller will return early and requeue the ICI CR after the DataImageCoolDownPeriod. This should prevent IBIO from adding the reboot annotation before BMO cached client notice that a DataImage exists.

MGMT-19188: BMO never mounted dataimage into IBI provisioned SNO

---

api/v1alpha1/imageclusterinstall_webhook.go
api/v1alpha1/imageclusterinstall_webhook_test.go

Installation always fails when MachineNetwork is not set and Proxy is set, so it's best to reject the creation of the ICI in the first place.
closes [MGMT-19107](https://issues.redhat.com//browse/MGMT-19107)

MGMT-19107: Make MachineNetwork required when setting Proxy

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go
internal/credentials/credentials.go
internal/credentials/credentials_test.go
internal/installer/installer.go

[MGMT-19206](https://issues.redhat.com//browse/MGMT-19206): installer should save seed reconfiguration file when creating the iso
It will be saved as inside working folder as cluster-configuration/manifest.json
New secret will be created with it's data

MGMT-19206: installer should save seed reconfiguration file when creating the iso

---

controllers/imageclusterinstall_monitor.go
controllers/imageclusterinstall_monitor_test.go

Currently if we reach the cluster installation timeout while the bmh is powered off, then we always set the reason to "ClusterInstallationInProgress" and the message to "Waiting for BMH to power on".
This pr adds a check to see if we reached the timeout, and if so sets the conditions accordingly.
closes  [MGMT-19203](https://issues.redhat.com//browse/MGMT-19203)

MGMT-19203: Update the reason in case of timeout while bmh is powered off

---

internal/installer/installer.go

This PR skips adding an empty CA bundle in the install-config, just for code readability/consistency, as later on we check if there is a non empty `caBundle`. 
PS. As far as I tested via the `openshift-install`, providing an empty `additionalTrustBundle` does not lead to any issues, it is just omitted. So that's purely a source code readability/maintainability change.

NO-ISSUE: Add CA bundle to install-config only when non empty

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go
internal/imageserver/imageserver.go

Make sure the clusterInfo file exists in case the bootTime is set
This would ensure the clusterInfo is regenerated in case the IBIO pod was restarted

MGMT-19341: IBIO isn't creating the config after restart for ICI with bootTime set

---

internal/credentials/credentials.go
internal/credentials/credentials_test.go

This ensures that the siteconfig operator will backup and restore these secrets when it is orchestrating a reinstall for IBBF
Resolves https://issues.redhat.com/browse/MGMT-19492
Additionally this PR moves the labels and owner references to the mutate function in `createOrUpdateClusterCredentialSecret` so that we can ensure those are always set.

MGMT-19492: Add siteconfig secret label

---

Dockerfile

[MCE 2.6] Fix the runtime base image

---

config/manager/manager.yaml

MCE's installer is adding additional security features to our deployment when it is run.
We should also add those to our deployment here to catch any issues they might cause in presubmits rather than only hitting them when QE gets a build from MCE.
Specifically the addition of readOnlyRootFilesystem caused https://issues.redhat.com/browse/MGMT-19745. This would have been found in a presubmit if it was here before the relevant changes were made.
Also sets TMPDIR env var to /data. Some dependencies (openshift/installer) also use temp storage so it's better to set TMPDIR for the whole process rather than trying to enforce temp files be written to /data in code.

MGMT-19745: Handle readOnlyRootFilesystem in pod deployments

---

.tekton/image-based-install-operator-mce-28-pull-request.yaml
.tekton/image-based-install-operator-mce-28-push.yaml
Dockerfile
Dockerfile.konflux

This PR makes the changes required to pass the konflux enterprise contract test.
This includes:
- setting labels on the Dockerfile so that the base image values are not inherited
- picking up some task changes from the konflux automated PRs (specifically https://github.com/openshift/image-based-install-operator/pull/197 and https://github.com/openshift/image-based-install-operator/pull/176)
- enabling hermetic builds (which also required removing the module download from the Dockerfile)
- setting some task parameters in specific ways
With all of this the konflux stuff seems to be passing which will allow us to merge cherry-pick PRs to 2.8 as we've just passed feature freeze.

Fix konflux enterprise contract test

---

config/manager/manager.yaml
config/webhook/manifests.yaml
config/webhook/service.yaml

Move away from the default name to avoid name colisions when being deployed in the same namespace as other services
https://issues.redhat.com/browse/MGMT-19972
cc @dislbenn @trewest

MGMT-19972: Rename webhook service

---

config/manager/manager.yaml
config/webhook/manifests.yaml
config/webhook/service.yaml

Move away from the default name to avoid name colisions when being deployed in the same namespace as other services
https://issues.redhat.com/browse/MGMT-19976

[backplane-2.8] MGMT-19976: Rename webhook service

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

The changes add a validation step in the ensureBMHDataImage method, the code now checks if a DataImage has a non-zero DeletionTimestamp and returns an explicit error if so.
Added a test case to verify that when a DataImage marked for deletion is processed, the controller sets the appropriate status condition and error message.

MGMT-20024: IBIO fails in case old dataImage exists and hangs during deletion.

---

controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_controller_test.go

In case dataImage exists make sure it's not marked for deletion, in case DeletionTimestamp is set update the ClusterInstallRequirementsMet condition with an informative message
Signed-off-by: Eran Cohen <eranco@redhat.com>

[backplane-2.8] MGMT-20069: IBIO fails in case old dataImage exists and hangs during deletion

---

cmd/manager/main.go
controllers/conditions.go
controllers/imageclusterinstall_controller.go
controllers/imageclusterinstall_monitor.go

The monitor will list existing ImageClusterInstall CRs and call client.Status.Update for all ICI that didn't complete the installation.
This should enqueue the ICI CRs for reconciliation when the controller starts

MGMT-20128: Image based install operator not reconciling after pod is  restarted

---

Dockerfile
bundle/manifests/image-based-install-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Without this the deployment with konflux images was failing with:
```
Error: container create failed: time="2025-09-24T13:24:55Z" level=error msg="runc create failed: unable to start container process: exec: \"/server\": stat /server: no such file or directory"
Error: container create failed: time="2025-09-24T13:24:55Z" level=error msg="runc create failed: unable to start container process: exec: \"/manager\": stat /manager: no such file or directory"
```
Resolves https://issues.redhat.com/browse/MGMT-21853

MGMT-21853: Change binary paths to /usr/local/bin

---

Dockerfile.konflux

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for image-based-install-operator-mce-29
